# Jashan Rai
range: lab7.o get_data.o print_all.o get_range_count.o lab7.h
	gcc lab7.o get_data.o print_all.o get_range_count.o -o range -lm

lab7.o: lab7.h

get_data.o: lab7.h

print_all.o: lab7.h

get_range_count.o: lab7.h
