# Jashan Rai Lab 9 Mini Shell


lab9: lab9.o ParseCmd.o lab9_10.h
	gcc lab9.o ParseCmd.o -Wall

lab9.o: lab9.c lab9_10.h
	gcc -c lab9.c

ParseCmd.o: ParseCmd.c lab9_10.h
	gcc -c ParseCmd.c
